// <auto-generated />
using System;
using BobaShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BobaShopApi.Migrations
{
    [DbContext(typeof(BobaShopContext))]
    [Migration("20250417173329_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BobaShopApi.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic Milk Tea",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Taro Milk Tea",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Matcha Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mango Smoothie",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Strawberry Lemonade",
                            Price = 3.75m
                        });
                });

            modelBuilder.Entity("BobaShopApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "John Doe",
                            Position = "Barista",
                            Salary = 30000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jane Smith",
                            Position = "Manager",
                            Salary = 50000m,
                            Shift = "Evening"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Alice Johnson",
                            Position = "Cashier",
                            Salary = 25000m,
                            Shift = "Afternoon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bob Brown",
                            Position = "Delivery",
                            Salary = 28000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Charlie Green",
                            Position = "Supervisor",
                            Salary = 40000m,
                            Shift = "Evening"
                        });
                });

            modelBuilder.Entity("BobaShopApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
