// <auto-generated />
using System;
using BobaShopApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BobaShopApi.Migrations
{
    [DbContext(typeof(BobaShopContext))]
    [Migration("20250430140126_updated_data_urls")]
    partial class updated_data_urls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BobaShopApi.Models.Drink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Classic Milk Tea",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Taro Milk Tea",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Matcha Latte",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mango Smoothie",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Strawberry Lemonade",
                            Price = 3.75m
                        },
                        new
                        {
                            Id = 6,
                            Name = "The blood of my enemies",
                            Price = 4.25m
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://example.com/vegan-juice.jpg",
                            Name = "Vegan Juice",
                            Price = 20.8m
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://www.bing.com/th/id/OIP.Gsl2sxyGt020l_KzrKqEHAHaFE?w=273&h=211&c=8&rs=1&qlt=90&o=6&dpr=2&pid=3.1&rm=2",
                            Name = "Peach Oolong Tea",
                            Price = 3.25m
                        });
                });

            modelBuilder.Entity("BobaShopApi.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jojo Siwa",
                            Position = "Matcha Man",
                            Salary = 10000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bella",
                            Position = "  Lawyer",
                            Salary = 500000m,
                            Shift = "Evening"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grayce Johnson",
                            Position = "Taster",
                            Salary = 250000m,
                            Shift = "Afternoon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cindy Cindy'sLastName",
                            Position = "Delivery",
                            Salary = 28000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 5,
                            Name = "General Trab",
                            Position = "HR",
                            Salary = 400000m,
                            Shift = "Evening"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Oliver JFK",
                            Position = "RadStreamer",
                            Salary = 320000m,
                            Shift = "Reasonable Hours"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shelly Jarsky",
                            Position = "Lead Scientist",
                            Salary = 5500000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Creature Jarsky",
                            Position = "Sad Intern",
                            Salary = 10m,
                            Shift = "Graveyard"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Numi Toffe",
                            Position = "Stay at Home Daughter",
                            Salary = 5000m,
                            Shift = "24/7"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Tia",
                            Position = "Writer",
                            Salary = 1000000m,
                            Shift = "Evening"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Lexi",
                            Position = "Vegan",
                            Salary = 2000000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Jennifer Kanna",
                            Position = "Estition",
                            Salary = 2000000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Josh",
                            Position = "Kanna's Assistant/Stay at Home Husband",
                            Salary = 20m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Yoni ",
                            Position = "Streamer",
                            Salary = 200000000m,
                            Shift = "Night"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lev",
                            Position = "Acedemic Weapon",
                            Salary = 1000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Lochnessa",
                            Position = "Manager",
                            Salary = 100000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Zoe Catluv7",
                            Position = "Marine Biologist",
                            Salary = 100000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Esme",
                            Position = "Japanese",
                            Salary = 100000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Barbie",
                            Position = "Being Hot",
                            Salary = 10000000000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Megan",
                            Position = "Stuff",
                            Salary = 100000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Alf",
                            Position = "Boba Maker",
                            Salary = 50m,
                            Shift = "Graveyard"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Riley Catluv7",
                            Position = "Boba Music/Zoe's Pet",
                            Salary = 30m,
                            Shift = "Graveyard"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Avery",
                            Position = "Professor",
                            Salary = 300000m,
                            Shift = "Morning"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Megan Catluv7",
                            Position = "Boba Music/Zoe's Pet",
                            Salary = 30m,
                            Shift = "Graveyard"
                        });
                });

            modelBuilder.Entity("BobaShopApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
